const Types = {
  FETCH_USERS_START: 'users/FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'users/FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR: 'users/FETCH_USERS_ERROR',
  FETCH_USER_START: 'users/FETCH_USER_START',
  FETCH_USER_SUCCESS: 'users/FETCH_USER_SUCCESS',
  FETCH_USER_ERROR: 'users/FETCH_USER_ERROR',

  SET_FAVOURITE_USERS: 'users/SET_FAVOURITE_USERS',
  LIKE_USER: 'users/LIKE_USER',
  UNLIKE_USER: 'users/UNLIKE_USER',

  CLEAR_USER: 'users/CLEAR_USER',
};

export default Types;
